adobe/asset-share-commons

CHANGELOG.md, core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareServiceImpl.java
@joerghoh ok - moved this to the EmailShareServiceImpl itself.
=> #27 - XSS Protect user input for Share emails

CHANGELOG.md
#53 was missing changelog entry
=> #53 - Added changelog for 53

core/src/main/java/com/adobe/aem/commons/assetshare/components/details/impl/ActionButtonsImpl.java
Fixes issue with ActionButtonsImpl binding to TagsImpl resource type
=> #52 - Fixed issue w incorrect RT binding for ActionButtonsImpl

ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/semantic-ui/modal.js
=> #43 - Modals should display in the center of the current view in Authoring Preview mode

ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/cart/cart.js
@davidjgonzalez PR has the changes to cart.js to trigger the cart clear event
=> added clear event trigger for the cart clear

CHANGELOG.md, ui.content/pom.xml
Removes unused configs in ui.content pom
=> #74 - Removed unused configurations in the ui.content project

CHANGELOG.md, core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/AbstractPredicate.java, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/search-page/_cq_dialog/asset-share-commons/actions/.content.xml
Fixes issue w groupId and wording around share action
=> #96 - v1.0.4 release bug-fixes

core/pom.xml, pom.xml, ui.apps/pom.xml, ui.content/pom.xml
update develop branch following release of master.
=> Merge Master into Develop

CHANGELOG.md, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/clientlibs/site/js.txt, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/clientlibs/site/js/cards.js
=> #113 - Left aligns result cards

CHANGELOG.md, ui.apps/src/main/content/jcr_root/etc/cloudsettings/asset-share-commons/contexthub/emulators/.content.xml, ui.apps/src/main/content/jcr_root/etc/cloudsettings/asset-share-commons/contexthub/eventdata/.content.xml, ui.apps/src/main/content/jcr_root/etc/cloudsettings/asset-share-commons/contexthub/geolocation/.content.xml, ui.apps/src/main/content/jcr_root/etc/cloudsettings/asset-share-commons/contexthub/pagedata/.content.xml, ui.apps/src/main/content/jcr_root/etc/cloudsettings/asset-share-commons/contexthub/profile/.content.xml, ui.apps/src/main/content/jcr_root/etc/cloudsettings/asset-share-commons/contexthub/recentlyviewed/.content.xml, ui.apps/src/main/content/jcr_root/etc/cloudsettings/asset-share-commons/contexthub/segmentation/.content.xml, ui.apps/src/main/content/jcr_root/etc/cloudsettings/asset-share-commons/contexthub/surferinfo/.content.xml
@godanny86 this is needed (with a 1.2.1 release) to unblock arpitha's deployment.
=> #123 - Adjusted how the OOTB store types are defined in XML

CHANGELOG.md, ui.apps/src/main/content/jcr_root/etc/cloudsettings/asset-share-commons/contexthub/emulators/.content.xml, ui.apps/src/main/content/jcr_root/etc/cloudsettings/asset-share-commons/contexthub/eventdata/.content.xml, ui.apps/src/main/content/jcr_root/etc/cloudsettings/asset-share-commons/contexthub/geolocation/.content.xml, ui.apps/src/main/content/jcr_root/etc/cloudsettings/asset-share-commons/contexthub/pagedata/.content.xml, ui.apps/src/main/content/jcr_root/etc/cloudsettings/asset-share-commons/contexthub/profile/.content.xml, ui.apps/src/main/content/jcr_root/etc/cloudsettings/asset-share-commons/contexthub/recentlyviewed/.content.xml, ui.apps/src/main/content/jcr_root/etc/cloudsettings/asset-share-commons/contexthub/segmentation/.content.xml, ui.apps/src/main/content/jcr_root/etc/cloudsettings/asset-share-commons/contexthub/surferinfo/.content.xml
=> v1.2.1 Release

ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/path/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/path/_cq_template/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/path/templates/options.html
Added auto-search to Path search component.
Skipping changelog as this is covered via 128/130
=> #128 / #130 - Added auto-search to Path search component

core/src/main/java/com/adobe/aem/commons/assetshare/search/impl/SearchImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/search/providers/impl/QuerySearchProviderImpl.java
Confirmed as working by Kikuchi
=> #152 - Fixed leaking querybuilder resource resolver

ui.content/src/main/content/jcr_root/content/asset-share-commons/en/.content.xml
=> removed contexthub segment on en page

CHANGELOG.md, core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/cart/impl/CartImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/dmdownload/impl/DynamicMediaDownloadImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/download/impl/DownloadImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/PagePredicateImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/configuration/impl/ConfigImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/configuration/impl/MessagesImpl.java, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/root/clientlibs/editor/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/root/clientlibs/editor/css.txt, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/root/clientlibs/editor/css/rail.less
=> v1.5.2 Release

ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/statistics/statistics.html
Hi,
When trying to test the display of the + sign next to the TOTAL number in the Statistics component, it didn't work.
I updated statistics.html and replaced component.more by component.hasMore to fix the issue.
=> Fixed issue with the display of the + sign

CHANGELOG.md, core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/impl/ActionPageServlet.java, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/semantic-ui/modal.js
Should resolve issue shown in issue #69.
=> #69 - Switch HTTP request to load Modals from GET to POST

CHANGELOG.md, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/config.author/com.adobe.granite.resourcestatus.impl.CompositeStatusType-asset-share-commons.xml
@davidjgonzalez @godanny86, curious to know if you have any suggestions on how to better future proof this to allow for product changes since this configuration replaces the default editor CompositeStatusType configuration.
=> [#227] Added workflow to the editor composite status type

core/src/main/java/com/adobe/aem/commons/assetshare/content/impl/MetadataSchemaPropertiesImpl.java, pom.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/details-page/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/page/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/page/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/search-page/_cq_dialog/.content.xml
1. Changed the WCM Core Components Version to 2.1.0
2. Updated Page Component to Supertype it to v2 version of WCM Core components
=> #192 -"Page Policy" template configuration option is missing

core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/PagePredicateImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/search/providers/impl/QuerySearchProviderImpl.java
=> #248 - Resolved issues with group merging done in #239

core/src/main/java/com/adobe/aem/commons/assetshare/search/providers/impl/QuerySearchProviderImpl.java
=> #248 - Corrected order of QB Predicate merging

core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/PagePredicate.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/PagePredicateImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/package-info.java
=> #260 - Added offset handling to the PagePredicate

core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/PagePredicate.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/PagePredicateImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/search/SearchConfig.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/search/impl/SearchConfigImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/search/providers/impl/QuerySearchProviderImpl.java, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/_cq_dialog/.content.xml
Uses SearchConfig from #252 
Added checkbox to Search Results compnent
/cc @Shaihuludus
=> Feature/253 - case sensitive sorting

core/src/main/java/com/adobe/aem/commons/assetshare/components/search/impl/SearchConfigImpl.java
Resolves issue with inability to instantiate SearchConfig mode i #276 
/cc @kaushalmall 
Thanks @justinedelson
=> #276 - Corrected SlingConfigImpl resource injector to be @SlingObject

core/src/main/java/com/adobe/aem/commons/assetshare/configuration/impl/AssetDetails404Servlet.java
=> Feature/send 404 #283

_pages/getting-started/set-up/index.md
=> update with sample filter rules

core/src/test/java/com/adobe/aem/commons/assetshare/README.md
ASC Unit Testing style guides. 
As part of this, new Java code requires reasonable code coverage following these approaches/standards.
/cc @joerghoh and @ireasor
=> #320 - Unit Testing Style Guide (DRAFT)

CHANGELOG.md, core/pom.xml
No changes, simply ran Reformat on the file in Intellij
=> #313 - Reformatted core/pom.xml

CHANGELOG.md, core/src/main/java/com/adobe/aem/commons/assetshare/configuration/impl/AssetDetailsResolverImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/search/impl/datasources/SearchPredicatesDataSource.java
…well
@HitmanInWis i think this should fix it - added GREEDY to AssetDetailsResolver as well.
=> #327 - Custom SearchPredicates (and AssetDetailResolvers) are not binding without bundle restart

CHANGELOG.md, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/filter-toggle/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/filter-toggle/filter-toggle.html, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/filter-toggle/templates/toggles.html
=> #303 - Add ability to hide the Apply Toggle Filter control

.codeclimate.yml, CHANGELOG.md, core/pom.xml
Screenshot of bundle import deployed to daily (today's)
=> Feature/359 - Import of xss API to support export of v2.0.1 (6.5)

CHANGELOG.md, core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/impl/ActionHelperImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareServiceImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/details/impl/ImageImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/details/impl/RenditionsImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/configuration/impl/AssetDetailsImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/configuration/impl/AssetDetailsResolverImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/AssetModel.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/impl/AssetModelImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/package-info.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/properties/impl/PathEncodedImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/properties/impl/PathEscapedImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/properties/impl/UrlImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/search/results/package-info.java, core/src/test/java/com/adobe/aem/commons/assetshare/content/impl/AssetModelImplTest.java, core/src/test/resources/com/adobe/aem/commons/assetshare/content/impl/AssetModelImplTest.json, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/title/title.html, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/cart/clientlibs/site/js/cart.js, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/clientlibs/site/js/download.js, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/download.html, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/share/clientlibs/site/js/share.js, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/share/share.html, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/result/card/templates/card.html
I believe this should resolve #340 and #358 by properly escaping URLs.
=> Feature/340 - Escaping URLs

CHANGELOG.md, core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/EmailShare.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/ShareException.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareServiceImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/package-info.java, core/src/main/java/com/adobe/aem/commons/assetshare/util/EmailService.java, core/src/main/java/com/adobe/aem/commons/assetshare/util/impl/EmailServiceImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/util/package-info.java, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/share/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/share/_cq_template/.content.xml, ui.content/src/main/content/jcr_root/content/asset-share-commons/en/dark/actions/share/.content.xml, ui.content/src/main/content/jcr_root/content/asset-share-commons/en/light/actions/share/.content.xml
add support for using sharer email as reply-to address
this can be configured by a checkbox in edit dialog
=> #366 add support for setting sharer email as reply-to address

CHANGELOG.md, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/share/_cq_dialog/.content.xml
=> Fix/388 - Corrected spelling of Boolean in reply to sharer dialog

.travis.yml, CHANGELOG.md, core/pom.xml, pom.xml
This was harder than expected - thought locally I don't have J11 yet, so had to rely on travis to build on J11. Travis now builds the project on both JDK8 and JDK11.
=> #398 - JDK11 support

.travis.yml, CHANGELOG.md, README.md, core/pom.xml, pom.xml
Got it to work ..
https://codecov.io/gh/Adobe-Marketing-Cloud/asset-share-commons/src/78ddba03a9c4030a496cf4e169ee6b3d8e5ecb2c/core/src/main/java/com/adobe/aem/commons/assetshare/util/PredicateUtil.java
=> #418 - CodeCov support

core/src/test/java/com/adobe/aem/commons/assetshare/components/details/impl/MetadataImplTest.java, core/src/test/resources/com/adobe/aem/commons/assetshare/components/details/impl/MetadataImpl.json
Updated MetadataImpl (Details component model) test to align with project standards.
=> Test - Details MetadataImpl

CHANGELOG.md, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/cart/clientlibs/site/js/cart.js
=> Fix for Issue #467

CHANGELOG.md, core/src/main/java/com/adobe/aem/commons/assetshare/components/details/impl/RenditionsImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/impl/datasources/AssetRenditionsDataSource.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/AssetRenditionDispatchers.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/AssetRenditions.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/AssetRenditionDispatchersImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/AssetRenditionServlet.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/AssetRenditionsImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/package-info.java, core/src/test/java/com/adobe/aem/commons/assetshare/content/impl/datasources/AssetRenditionsDataSourceTest.java, core/src/test/java/com/adobe/aem/commons/assetshare/content/renditions/impl/AssetRenditionDispatchersImplTest.java, core/src/test/java/com/adobe/aem/commons/assetshare/content/renditions/impl/AssetRenditionServletTest.java, core/src/test/java/com/adobe/aem/commons/assetshare/content/renditions/impl/AssetRenditionsImplTest.java
=> Fix/502 for 1.x - Cyclic dependency

ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/property/_cq_dialog/.content.xml
fix for issue - 560 remove extra radio button https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/560
=> fix for issue - 560 remove extra radio button https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/560

all/pom.xml, core/pom.xml, core/src/main/java/com/adobe/aem/commons/assetshare/content/properties/impl/AssetRenditionImpl.java, pom.xml, ui.apps/pom.xml, ui.content/pom.xml
initial commit to include both aem sdk and uber jar
=> Include aem sdk

ui.apps/src/main/content/jcr_root/apps/asset-share-commons/config.author/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-asset-share-commons.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/config.publish/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-asset-share-commons.xml, ui.content.sample/src/main/content/jcr_root/_oak_index/_rep_policy.xml
Cloud Manager deploy fixes (required to deploy to AEM as a Cloud Service via CM)
=> 2.0.0/cloud manager deploy

ui.apps/src/main/content/jcr_root/apps/asset-share-commons/authoring/renderconditions/require-aem/require-aem.jsp, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/image/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/renditions/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/video/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/search-page/_cq_dialog/asset-share-commons/actions/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/search-page/_cq_dialog/asset-share-commons/messages/.content.xml
Rendercondition for AEM as a Cloud Service vs. 6.5.
Tried to hide everything I could think of appropriately - well probably have to add stuff when we do regressions.
=> 2.0.0/render condition

core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/downloads/impl/PlaceholderDownloadEntry.java, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/authoring/renderconditions/require-aem/require-aem.jsp, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/download.js, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/download.html, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/downloads/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/downloads/downloads.html, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/downloads/templates/download.html, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/downloads/templates/downloads-lists.html
1. Fixed some issues w/ Downloads component when using Placeholder
2. Added ability to toggle on Automatic downloads (alot to help w/ debugging :)) in Download Modal component
3. Added label fields to Downloads component
4. Corrected some logic in require-aem render condition
5. other minor tweaks
=> 2.0.0/dialogs and cleanup

_pages/content/index.md
=> Typo - AWM -> AEM

CHANGELOG.md, all/pom.xml
Fixed #607. Removes the hard package dependency on Core Components.=
See #607 - Breaks AEM CS deployments after the April 1st AEM CS release
Against AEM SDK
=> #607 - Removed hard dependency on core components package

all/pom.xml, core/pom.xml, dispatcher/pom.xml, pom.xml, ui.apps.structure/pom.xml, ui.apps/pom.xml, ui.content.sample/pom.xml, ui.content/pom.xml, ui.frontend.theme.dark/pom.xml, ui.frontend.theme.light/pom.xml
=> v2.0.5-SNAPSHOT

CHANGELOG.md, core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/async/impl/ExpressionDownloadArchiveNamer.java, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/download.js
=> #644 - Fixed invalid reference to donwnloadId

ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/download.js
Fixed issue in original PR of #644 where the wrong variable was passed into _poll(..)
=> #644 - Fixed undefined downloadId

core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/AssetRendition.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/ExternalRedirectRenditionDispatcherImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/util/UrlUtil.java, core/src/test/java/com/adobe/aem/commons/assetshare/content/renditions/AssetRenditionTest.java, core/src/test/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/ExternalRedirectRenditionDispatcherImplTest.java
=> External Redirect URL fix

_includes/sidebar.html, _pages/getting-started/new-project/index.md, _pages/getting-started/set-up/index.md
Added a guide to creating a new project and a reference to a sample implementation: https://github.com/godanny86/wknd-asset-share
How to make:
=> added new project guide

CHANGELOG.md, core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/downloads/Downloads.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/async/DownloadEntry.java
=> 0620 - Fixed issue with Javadoc syntax that caused warnings

.github/workflows/maven.yml
Align to Adobe standard, avoiding Azul
=> Change Github action to build with temurin

core/pom.xml
=> Don't export conditional packages

core/src/main/java/com/adobe/aem/commons/assetshare/search/providers/impl/QuerySearchProviderImpl.java
=> Trim all search request parameter values

pom.xml, ui.frontend.theme.dark/package-lock.json, ui.frontend.theme.light/package-lock.json
Use frontend-m-p 1.12.1
This closes #731
=> Update Node and NPM to latest LTS version

core/pom.xml, core/src/test/java/com/adobe/aem/commons/assetshare/components/actions/download/impl/AsyncAssetRenditionsDownloadServletTest.java, core/src/test/java/com/adobe/aem/commons/assetshare/content/impl/datasources/AssetRenditionsDataSourceTest.java, core/src/test/java/com/adobe/aem/commons/assetshare/content/renditions/download/impl/AssetRenditionsDownloadServletTest.java, core/src/test/java/com/adobe/aem/commons/assetshare/content/renditions/impl/AssetRenditionServletTest.java, pom.xml
Reduce transitive dependencies of core bundle
This closes #729
=> Enable OWASP dependency-check

core/src/main/java/com/adobe/aem/commons/assetshare/content/properties/impl/AssetTypeImpl.java, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/config.author/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-asset-share-commons-author.config, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/config.author/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-asset-share-commons.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/config.publish/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-asset-share-commons.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/config/org.apache.sling.jcr.repoinit.RepositoryInitializer-asset-share-commons-all.config, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended~asset-share-commons-all.config
=> Use service resource resolver for accessing mimetypeLookup resource

.github/workflows/maven.yml
=> Trigger Maven build for each commit to develop, main or master

CHANGELOG.md, all/pom.xml, core/pom.xml, core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/AssetRenditionsImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/util/ExpressionEvaluator.java, core/src/main/java/com/adobe/aem/commons/assetshare/util/impl/ExpressionEvaluatorImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/util/package-info.java, core/src/test/java/com/adobe/aem/commons/assetshare/util/impl/ExpressionEvaluatorImplTest.java, core/src/test/resources/com/adobe/aem/commons/assetshare/util/impl/ExpressionEvaluatorImplTest.json, dispatcher/pom.xml, pom.xml, ui.apps.structure/pom.xml, ui.apps/pom.xml, ui.content.sample/pom.xml, ui.content/pom.xml, ui.frontend.theme.dark/pom.xml, ui.frontend.theme.light/pom.xml
Support using relative property paths in Expression Evaluation, in the format:
paths are relative to the `[dam:Asset]/jcr:content/metadata` resource, or via a computedProperty.
The property will be evaluated as `assetModel.getProperties(propertyName, "")` so the value must be coercible to a String.
```
"http://foo.com/${prop@myMetadataProperty}" <-- property name, resolved off the metadata node
"http://foo.com/${prop@../jcr:content/myJcrContentProperty}" <-- relative property path
"http://foo.com/${prop@type}" <-- computed property
```
=> Property-based expression evaluation

ui.apps/src/main/content/META-INF/vault/filter.xml
=> Remove pre 2.3.0 OSGi configuration

.github/workflows/snapshot-deploy.yaml, .github/workflows/verify.yaml, pom.xml, ui.apps/src/main/content/META-INF/vault/filter.xml
=> v2.3.4 release merge

core.cloud/pom.xml, core/pom.xml, pom.xml
Remove unused slf4j-test dependency
=> Update sling-mock to 3.3.2 and osgi-mock to 3.3.0

pom.xml
version 3.0.0-M5 is breaking release process.
=> Updated maven-release-plugin version to 3.0.0-M6

.github/workflows/maven-release.yml, .github/workflows/snapshot-deploy.yaml, .github/workflows/verify.yaml
=> enable "cloud" profile for all CI builds and release

.github/workflows/maven-release.yml, .github/workflows/snapshot-deploy.yaml, .github/workflows/verify.yaml
v3.2.6 github action release updates
=> v3.2.6 github action release updates 

ui.apps/pom.xml, ui.config/pom.xml, ui.content.sample/pom.xml, ui.content/pom.xml
filevault-package-maven-plugin (packaging) and
content-package-maven-plugin (deployment)
=> Set final name of content packages for both

core/pom.xml, pom.xml
=> Also load DS components and Sling Models from fragment bundles

CHANGELOG.md, core/pom.xml, pom.xml, ui.apps/pom.xml, ui.config/pom.xml, ui.content.sample/pom.xml, ui.content/pom.xml
=> v.2.4.1 Release

ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-author/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-base/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-dependencies/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/vendor/formdata-polyfill/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/vendor/jquery/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/vendor/modernizr/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/vendor/moment/.content.xml
Minify with GCC supporting ECMA 2015
This closes #837
=> Minify only when necessary

.github/workflows/maven-release.yml, CHANGELOG.md, all/pom.xml, core.cloud/pom.xml, core/pom.xml, dispatcher/pom.xml, pom.xml, ui.apps.structure/pom.xml, ui.apps/pom.xml, ui.config/pom.xml, ui.content.sample/pom.xml, ui.content/pom.xml, ui.frontend.theme.dark/pom.xml, ui.frontend.theme.light/pom.xml
=> v2.4.4 release

core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareServiceImpl.java, pom.xml, ui.frontend.theme.dark/package-lock.json, ui.frontend.theme.light/package-lock.json
=> v2.4.8 release

core/src/main/java/com/adobe/aem/commons/assetshare/components/assetkit/AssetKit.java, core/src/main/java/com/adobe/aem/commons/assetshare/util/assetkit/AssetKitHelper.java, core/src/main/java/com/adobe/aem/commons/assetshare/util/assetkit/ComponentUpdater.java, core/src/main/java/com/adobe/aem/commons/assetshare/util/assetkit/PagePathGenerator.java, core/src/main/java/com/adobe/aem/commons/assetshare/util/assetkit/impl/componentupdaters/AssetKitComponentUpdaterImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/util/assetkit/impl/componentupdaters/BannerComponentUpdaterImpl.java, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/asset-kit/asset-kit.html, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/asset-kit/clientlibs/site/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/asset-kit/clientlibs/site/js/asset-kit.js, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/asset-kit/clientlibs/site/less/asset-kit.less, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/workflow/asset-kit/asset-kit-creator/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/workflow/asset-kit/asset-kit-creator/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/workflow/asset-kit/asset-kit-replicator/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/workflow/asset-kit/asset-kit-replicator/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/workflow/asset-kit/asset-kit-replicator/_cq_editConfig.xml
=> Asset kit fixes (help URLs, OSGi configurations and naming)

all/pom.xml, core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/ShareService.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareServiceImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/ShareServlet.java, pom.xml
=> Removed all escaping for controlled email variables

ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/search/search-form.js, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/semantic-ui/plug-ins.js, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/property/templates/options.html
=> Fixed issue with daterange.upperBound predicate restrictions

.github/workflows/maven-release.yml
=> Release workaround

core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/PropertyPredicateImpl.java
Fixes possible NPE that is warn'ed about in logs.
=> Fix possible NPE in PropertyPredicateImpl

all/pom.xml, core.cloud/pom.xml, core/pom.xml, dispatcher/pom.xml, pom.xml, ui.apps.structure/pom.xml, ui.apps/pom.xml, ui.config/pom.xml, ui.content.sample/pom.xml, ui.content/pom.xml, ui.frontend.theme.dark/pom.xml, ui.frontend.theme.light/pom.xml
=> Fixed version from 3.50.0 to 3.5.0

ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/form-data.js, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/clientlibs/site/js/download.js, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/download.html
=> Single download for review

.github/workflows/maven-release.yml, .github/workflows/snapshot-deploy.yaml, .github/workflows/verify.yaml, pom.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/form-data.js, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/clientlibs/site/js/download.js, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/download.html, ui.content.sample/src/main/content/jcr_root/content/asset-share-commons/en/dark/.content.xml, ui.content.sample/src/main/content/jcr_root/content/asset-share-commons/en/light/.content.xml
=> v3.6.0 release

ui.frontend.theme.dark/package-lock.json, ui.frontend.theme.dark/package.json, ui.frontend.theme.light/package-lock.json, ui.frontend.theme.light/package.json
=> Updated jquery to 3.5.1

core/src/main/java/com/adobe/aem/commons/assetshare/configuration/impl/ConfigImpl.java, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/header/clientlibs/site/less/header.less, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/header/header.html, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/user-menu/user-menu.html
The downloads icon in the user-men is not showing properly.
Bugfix
On AEM SDK using mobile/tablet/desktop breakpoints.
=> Resolves issue #1095 where downloads icon is not showing properly

ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/search/search.js
=> Handle using the back/forward button on the search page

ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/pdf/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/video/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/_cq_template/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/share/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/common/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/date-range/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/freeform-text/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/path/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/property/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/sort/_cq_dialog/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/tags/_cq_dialog/.content.xml
=> Added missing cq: namespace

ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/clientlibs/site/less/card.less
Fixes #1147 search results card alignment
=> #1147 - Search results cards alignment

core/src/main/java/com/adobe/aem/commons/assetshare/util/impl/JsonResolverImpl.java
It is crashing the whole page. Log formatter will automatically cast the object.
=> Fixed issue 1171 : JSON option in Property Filter component is throwing UnsupportedOperationException

package-lock.json, pom.xml, ui.frontend.theme.dark/package-lock.json, ui.frontend.theme.light/package-lock.json
=> Updated node version to 14

all/pom.xml, core.cloud/pom.xml, core/pom.xml, core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/AssetRenditionDispatcher.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/AssetRenditionParameters.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/AssetRenditionServlet.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/ExternalRedirectRenditionDispatcherImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/StaticRenditionDispatcherImpl.java, core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/package-info.java, dispatcher/pom.xml, pom.xml, ui.apps.structure/pom.xml, ui.apps/pom.xml, ui.config/pom.xml, ui.content.sample/pom.xml, ui.content/pom.xml, ui.frontend.theme.dark/pom.xml, ui.frontend.theme.light/pom.xml
Allows for (more) accurate extensions for rendition downloads.
=> Rendition details

core/pom.xml
=> Try relaxing imports again for AEM SP18

ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/cart/cart.html, ui.frontend.theme.dark/package-lock.json, ui.frontend.theme.light/package-lock.json
There was a spelling mistake in the Download Cart button where the CSS class `positive` was incorrectly spelt `postive`. This spelling mistake seems to have had no visible impact.
https://github.com/adobe/asset-share-commons/issues/1264
Fix for minor spelling mistake in the Cart that means the the styling for the Download Cart button is not quite correct.
I have not been able to see a visible change after the fix.
Tested locally on author environment both by editing the page HTML directly in Chrome and by code changes.
Tested on AEMaaCS in an IBM iX Partner Sandbox project author environment by editing the page HTML directly in Chrome.
***Broken***
***Corrected***
=> Fix spelling mistake in Cart Download Cart button class

ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/clientlibs/site/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/downloads/clientlibs/site/.content.xml, ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/clientlibs/site/.content.xml
=> Removed JS Processing on clientlibs that use ES6 syntax
