- CHANGELOG.md
- ui.content/pom.xml
Skips deploy by default when performing mvn releases for this artifact (as we only upload to GitHub releases and not to bintray, as this is sample content).
> #11 - Skip ui.content deploy by default

- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/user-menu/user-menu.html
property names did not match policy dialog property. Fixes #53.
> 53 - using incorrect property for login and logout links

- CHANGELOG.md
- core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareServiceImpl.java
This seems to resolve the issues with EmailService not resolving properly. Can someone experiencing the problem verify this? I was able to reproduce (prior to this fix) by:
1) Installing ASC
2) Installing ACS Commons 3.11.0
After explicitly marking this dependency as Dynamic i am unable to reproduce the issues. (ASC EmailShareServiceImpl comes and goes (active/unsatisfied) with the ACS Commons EmailService availability.
> #29 - Marks (ACS Commons) EmailService reference as Dynamic

- CHANGELOG.md
- pom.xml
- ui.apps/pom.xml
- ui.content/pom.xml
- added ui.content to Parent pom.xml modules to fix Issue #56 
- removed autoInstallPackage and autoInstallPackagePublish profiles from ui.content so that it is built but not deployed
- NOTE* ui.content will always be built but not deployed with standard maven profiles. Don't see this as a big issue since most projects will include ui.apps and core directly via a project specific maven pom
> Bugfix/56 single release ui.content

- CHANGELOG.md
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/download.html
@harincar what do you think about this wrt to #108 
Added checkbox to exclude original from dialog, since the end-user may not realize if the original is too big or not to attempt.
If the original is excluded then the Include Renditions checkbox is force-selected.
> #108 - Add option to exclude original assets from download

- .github/config.yml
- CHANGELOG.md
- core/pom.xml
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/AbstractPredicate.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/FulltextPredicate.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/HiddenPredicate.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/PathPredicate.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/Predicate.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/PropertyPredicate.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/TagsPredicate.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/DatePredicateImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/PagePredicateImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/PathPredicateImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/PropertyPredicateImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/TagsPredicateImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/options/UnselectedOptionItem.java
- core/src/main/java/com/adobe/aem/commons/assetshare/search/providers/impl/QuerySearchProviderImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/util/PredicateUtil.java
- core/src/test/com/adobe/aem/commons/assetshare/util/PredicateUtilTest.java
- pom.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/path/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/path/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/path/_cq_editConfig/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/path/_cq_htmlTag/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/path/path.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/path/templates/options.html
Fixes #128
This also includes a fix i discovered where the query parameters were not setting the intial search form state (for example, check some filter check-boxes, perform a the search, and refresh the page using the query params to "save" the search) .. the search will perform however the filter input fields will not be updated to match the query params.
> #128 - Path Filter search component

- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/AbstractPredicate.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/Predicate.java
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/search/search.js
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/semantic-ui/plug-ins.js
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/date-range/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/date-range/_cq_template/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/date-range/templates/options.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/property/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/property/_cq_template/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/property/templates/options.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/sort/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/sort/_cq_template/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/sort/sort.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/tags/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/tags/_cq_template/.content.xml
Effects predicate components:
* Property
* Tags
* Sort
* PathFilter will need to be updated after merge (#128)
This feature adds a checkbox the the above components, so whenever an end user changes the component value (ie. clicks a checkbox, etc.) then a search is immediately preformed and they do not have to click "apply".
> #130 - Added support for auto-searching on predicate search components

- CHANGELOG.md
- core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/EmailShare.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/ShareService.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareServiceImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/ShareServlet.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/package-info.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/impl/datasources/ComputedPropertiesDataSource.java
- pom.xml
Supports multiple ShareService implementations. If none accept, then the default ASC email based ShareService is used.
Note that MULTIPLE share services can be invoked via a single share operation.
> #134 - Multiple ShareService support.

- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/resources/placeholder.jpeg/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/resources/placeholder.pdf/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/resources/placeholder.pptx/.content.xml
Issue details: https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/189
@godanny86 , please review.
> Removing versionable mixin type from /apps

- CHANGELOG.md
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/form-data.js
Fixes 195 - Search does not work in IE11 - replaced findIndex() & find() methods with polyfill methods.
> Feature/195 - IE11 JS incompatabilities

- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/root/clientlibs/editor/css/rail.less
Fix for Issue [#204 ](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/204)
> Issue#204: For mobile and tablet view, the filter rail should slide from left

- core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareServiceImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/configuration/AssetDetails.java
- core/src/main/java/com/adobe/aem/commons/assetshare/configuration/AssetDetailsResolver.java
- core/src/main/java/com/adobe/aem/commons/assetshare/configuration/Config.java
- core/src/main/java/com/adobe/aem/commons/assetshare/configuration/impl/AssetDetailsImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/configuration/impl/AssetDetailsResolverImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/configuration/impl/ConfigImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/configuration/package-info.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/impl/AssetResolverImpl.java
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/cart/cart.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/result/card/templates/card.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/result/list/templates/list.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/search-page/_cq_dialog/asset-share-commons/asset-details/.content.xml
Handles links from search results and e-mail sharing. Does NOT tackle the cart (which still stores by path). Configurable via Page Properties...
> #206 - Support asset details reference by Asset ID

- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download-dynamic-media/download-dynamic-media.html
Fix the test to display download options or not in the download-dynamic-media component.
> display download options when presets not empty

- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/PagePredicateImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/search/SearchConfig.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/search/impl/SearchConfigImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/search/package-info.java
- core/src/main/java/com/adobe/aem/commons/assetshare/search/impl/SearchImpl.java
Updating models to do a better job of "finding" the correct resource(s) on the page that represent the Search component.
This allows Sling Models to be created from various resources, yet still "resolve" to the right resource (and get the appropriate properties) with the model instantiator not having to know which/how to find the right resource.
> #249 - Search Model cache issues

- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/SortPredicate.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/PagePredicateImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/SortPredicateImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/package-info.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/search/SearchConfig.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/search/impl/SearchConfigImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/search/package-info.java
- core/src/main/java/com/adobe/aem/commons/assetshare/search/impl/SearchImpl.java
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/sort/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/sort/sort.html
This should resolve 254 and 255, though it builds on #252 (to get the SearchConfig for default values).
This PR removes the need (as well as the dialog fields) for the author'd "default" labels completely, since there is always some sort order.
Would some feedback on handling when the Sort component doesn't have a configured field that will match the default sort order of the Search Results component... in this PR it will list the label as: "Unknown". 
/cc @Shaihuludus
> Feature/254/255 - Sort labels

- pom.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/details-page/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/page/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/page/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/search-page/_cq_dialog/.content.xml
This unfortunately resurrects issue #192 ... 
we'll need another release that breaks backwards compat but includes this fix.
> #275 - Revert Core Components dep from 2.1.0 to 1.1.0

- CHANGELOG.md
- core/src/main/java/com/adobe/aem/commons/assetshare/components/details/impl/ImageImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/details/package-info.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/search/impl/SearchConfigImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/impl/datasources/ComputedPropertiesDataSource.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/properties/impl/ThumbnailImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/properties/impl/WebRenditionImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/util/MimeTypeHelper.java
- core/src/main/java/com/adobe/aem/commons/assetshare/util/impl/MimeTypeHelperImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/util/package-info.java
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/image/clientlibs/site/js.txt
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/image/clientlibs/site/js/image.js
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/image/image.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/cart/cart.html
Helps resolve issues described in #307/#308 where image previews/thumbnails are broken for unsupported (by the browser)(sometimes image) file formats.
/cc @HitmanInWis
> 307/308 - Handle displaying images for non-image assets better

- CHANGELOG.md
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/cart/clientlibs/site/js/cart-actions.js
- ui.content/src/main/content/jcr_root/conf/asset-share-commons/settings/wcm/templates/search-template-dark/initial/.content.xml
- ui.content/src/main/content/jcr_root/content/asset-share-commons/en/dark/.content.xml
- ui.content/src/main/content/jcr_root/content/asset-share-commons/en/light/.content.xml
Fixed an issue where `cart-remove` node is not created in initial content, creating a situation where opening and saving page properties on the search page causes the "Removed from Cart" notification to no longer fire due to a rogue `cart-exists` node under messages that is not used for anything.
> Fixed invalid content reference - cart-remove vs cart-exists

- CHANGELOG.md
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/share/_cq_dialog/.content.xml
In the cq:template file and the share.html of the share modal component, a reference is made to the `errorTitle` property, while the value in the dialog is `./errorText`.
All values are prefilled in the dialog, except for the error title. Making adjustments to this field in the dialog will not impact the value in the jcr since it is storing its value in `./errorText` instead of `./errorTitle`.
Given the standard naming convention (`modalTitle`, `successTitle`,...) I aligned the property name to `errorTitle`. No change to the cq:template or html is required since they already use `errorTitle`.
> Align error title property to "errorTitle"

- CHANGELOG.md
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/user-menu/clientlibs/site/js/profile.js
init user menu (profile.js) not only on profile store 'update' but also on profile store 'ready' event to make sure the user name is displayed on the subsequent page loads
> #163 init user menu when profile store is ready or gets updated

- CHANGELOG.md
- core/src/main/java/com/adobe/aem/commons/assetshare/content/impl/MetadataSchemaPropertiesImpl.java
- core/src/test/java/com/adobe/aem/commons/assetshare/content/impl/MetadataSchemaPropertiesImplTest.java
Added ability to specify, at a global level, via OSGi configuration
* Extra metadata properties - this allows for the addition of properties that may not make sense to show up in the Metadata Schema (even as Read-only)
* Blacklisted metadata properties - this allows for listing properties that should not show up as available Metadata schema properties to select from.
> Feature/374 - Metadata Schema Properties - Extra Metadata Properties and Blacklist Metadata Properties

- CHANGELOG.md
- Jenkinsfile
- pom.xml
This change should allow administrators to release the project using the ASC Jenkins instance [here (requires Adobe VPN)](https://acs.ci.corp.adobe.com/blue/pipelines).
Prerequisites:
* Don't set the version in the CHANGELOG.md - the first entry's title must be `[Unreleased]`
This pipeline accomplishes the following.
* Identify the current version
* Allow release admin to pick the release type - updates version based on last release.
* Update the Changelog with the new version
* Commits Changelog to `develop`
* Merges `develop` -> `master` for the release.
* Pushes up to Master.
* Performs a `maven release:prepare` using new version
* Performs a `maven release:perform`, including pushing all artifacts to Bintray
* Back merges snapshot poms to Develop
* Prepares the Changelog for the next …
> Release automation support.

- CHANGELOG.md
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/PagePredicate.java
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/form-data.js
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/filter-toggle/filter-toggle.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/result/templates/common.html
Fix issues with IE11 form submission since IE11 does not seem to respect the form element's form attribute to group inputs outside a `<form>` tag.
All form elements for submission must have `<some-form-el form="asset-share-commons__form-id__1"/>`
> Feature/458 - Fixes Search Form submission in IE11

- all/pom.xml
- core/pom.xml
- pom.xml
- release.properties
- repository-structure/pom.xml
- ui.apps/pom.xml
- ui.content.sample/pom.xml
- ui.content/pom.xml
Fixing issues described in https://github.com/Adobe-Marketing-Cloud/asset-share-commons/pull/486
resulting in:
> 479 - Align ASC to Maven Archetype 22 and AEM as a Cloud Service

- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js.txt
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/navigation.js
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/search/search.js
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/util.js
When ASC is used inside an iframe that doesn't have the same origin with the top (parent) frame, there are js security exceptions thrown.
This PR addresses these issues by checking wether the AEM frame has the same origin with the top frame. If it does, it doesn't alter the current behaviour. Otherwise only the iframe's URL is modified.
> Fix js errors when the top frame doesn't have the same origin

- core/src/main/java/com/adobe/aem/commons/assetshare/configuration/Config.java
- core/src/main/java/com/adobe/aem/commons/assetshare/configuration/impl/ConfigImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/configuration/package-info.java
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/cart/cart.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/page/init.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/search-page/_cq_dialog/asset-share-commons/actions/.content.xml
Draft PR for #550 
In some prelim testing it seems to work well, but likely needs a bit more testing before it can be merged. I used true/false for the values to maintain backwards compatibility while also extending to have "cart" as an option to enable those actions only for the cart.
> Extended the configuration to allow download/share only via the cart.

- all/pom.xml
- pom.xml
- ui.apps/pom.xml
- Ups the Core Component dependency version to 2.14.0 (can move to 2.15.0 once its available in the Cloud)
- Removes the Core Component Embed from the `all` module
- Moves the Asset Share Commons Core module embed into the `all` module
Affect on implementations:
- For Cloud Service implementations Core Components are automatically available, no effect
- For 6.5,6.4 customer implementations will be responsible for also embedding a compatible version of Core Components in their own project (in addition to Asset Share Commons dependencies)
> removing core component embed

- core/src/main/java/com/adobe/aem/commons/assetshare/configuration/impl/MessagesImpl.java
- If the text value in the dialog for a message is not set, the message
banner will still show with an empty message
- The logic for isMessageEmpty will currently never return false because
the message fieldsets contain a hidden field equal to the event id
- The message style does not allow for an empty input in the dropdown
options and if an empty value is passed to the component it will not
render the message properly.
- There is a property `label` that is used in the method that I cannot
find used in any other place at any other given time in the commit
history.
- I have removed the propety logic referencing `label` as it is not used
in anything I can see in the reference implementation and it makes the
isBlank check more difficult since well - in the reference its always
empty.
- I …
> Modifying the logic of the MessagesImpl.isMessageEmpty method

- CHANGELOG.md
- all/pom.xml
- pom.xml
ASC should not be installable if Core Components are not present on AEM. This adds a package dependency on ASC all package on immutable Core Components package(currently at v2.14.0). 
(You cannot package depend on a container package, thus we pick the immtuable package)
> Feature/578b - ASC All package depends on Core Components

- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/user-menu/user-menu.html
Issue:
Hamburger menu's close icon is not loading
Fix:
I don't see a semantic ui icon class by name "close outline". Hence, updated user-menu.html by removing the usage of class "outline"
> Removed the class "outline" for the semantic ui icon "close"

- core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/download/Download.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/downloads/impl/PlaceholderDownloadProgress.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/impl/AssetModelImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/async/impl/AsyncAssetRenditionsDownloadServlet.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/impl/AssetRenditionDownloadRequest.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/impl/AssetRenditionsDownloadServlet.java
Fixes issues called out by Cloud Manager code quality.
The only ones left should be use of deprecated APIs (most are our own deprecations which can kill in 3.0.0) but also a few for things like SlingSettingsService (for stuff like EditorLinks that should only work on AEM Author)
> 2.0.0/Cloud Manager code quality

- core/src/main/java/com/adobe/aem/commons/assetshare/configuration/impl/ConfigImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/async/impl/AsyncAssetRenditionsDownloadServlet.java
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/semantic-ui/modal.js
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/clientlibs/site/js/download.js
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/download.html
- adds new tab to Download dialog
- allows user to enable Direct Downloads
- when enabled, the download dialog modal will not appear. Instead it will be submitted silently. In order to function properly at least one rendition should be selected. The safest (and easiest) approach is to use direct downloads with the **original** rendition, since all asset types will have this. However it is also possible to check multiple renditions (assuming that all of the assets users can download will include this)
- Other modals continue to appear (License, Cart) and when the Download modal is called it will auto-submit the download.
Dialog option:
When direct download enabled a warning appears when editing the Download Modal (will never be shown to the end user)
> Direct download

- CHANGELOG.md
- core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/async/impl/DownloadEntryImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/ExternalRedirectRenditionDispatcherImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/InternalRedirectRenditionDispatcherImpl.java
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/downloads/_cq_dialog/.content.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/downloads/downloads.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/downloads/templates/download.html
See #662 
* Replaced ExternalRedirectRenditionDispatcherImpl's setting of 0 byte rendition size with 100MB as Oak no longer supports 0 bytes (and will fail the entire download/throw exception)
* Commented Download Size column from Downloads components as we cannot actually accurately/consistently compute the zip size using available APIs.
* Commented out so hopefully when the AEM API provides the actual zip size, we can uncomment or revert as needed. 
Tested on AEM CS using static and dynamic media renditions.
> Fix/662 - Replaced 0byte placeholder size with 100MB to prevent Oak exceptions

- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/action-buttons/action-buttons.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/editor-links/editor-links.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/metadata/metadata.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/renditions/renditions.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/tags/tags.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/video/video.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/cart/cart.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/download.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/templates/legacy.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/license/license.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/share/share.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/date-range/templates/options.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/filter-toggle/templates/toggles.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/freeform-text/freeform-text.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/layout-toggle/layout-toggle.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/result/card/templates/card.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/result/horizontal-masonry-card/templates/card.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/result/templates/common.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/search-bar/search-bar.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/sort/sort.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/statistics/statistics.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/structure/user-menu/templates/profile.html
I added @i18n to several components that were using properties from Dialogs or Policies without applying the I18N
- I took [downloads component](https://github.com/adobe/asset-share-commons/blob/261238d49c5e16b2e40f29f347c80801cd3c330f/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/downloads/downloads.html#L88) as an example and I added "@ i18n" to components that didn't have it, for instance the [cart component](https://github.com/adobe/asset-share-commons/blob/261238d49c5e16b2e40f29f347c80801cd3c330f/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/cart/cart.html#L87).
- Following the downloads component as an example I added the default literal that I could find in the corresponding _cq_template node.
#690 
Add I18N to the …
> #690 Added missing default labels with @ i18N

- core/pom.xml
- pom.xml
This ensures that all necessary transitive classes are embedded as well This closes #834
Unfortunately I was not able to reproduce the bug locally. @dsandqui Please give it a try.
> Embed ACS AEM Commons sources and recompile

- .github/workflows/maven-release.yml
Fixes deprecation notices reported at: https://github.com/adobe/asset-share-commons/actions/runs/3347887669
N/A
Github warning that deprecated methods will be removed.
Not yet!
> Replace deprecated set-output command with >> $GITHUB_OUTPUT

- core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareServiceImpl.java
Email are double-encoding characters such as `&`.
When a share description of `hello & world` is added, the share emails displays `hello &amp; world`. This is due to double encoding of data.
Sent myself a test email after the fix:
- [] My change requires a change to the documentation.
> HTML email values are being double-encoded in the Share email

- all/pom.xml
- core.cloud/pom.xml
- core.cloud/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/async/DownloadTargetParameters.java
- core.cloud/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/async/impl/AsyncAssetRenditionsDownloadServlet.java
- core.cloud/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/async/impl/NamedRenditionDownloadTargetProcessor.java
- core.cloud/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/download/async/package-info.java
- core.cloud/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/AssetDeliveryRenditionDispatcherImpl.java
- core/pom.xml
- core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/AssetRenditionParameters.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/AssetRenditionTracker.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/ExternalRedirectRenditionDispatcherImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/InternalRedirectRenditionDispatcherImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/StaticRenditionDispatcherImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/package-info.java
- dispatcher/pom.xml
- pom.xml
- ui.apps.structure/pom.xml
- ui.apps/pom.xml
- ui.config/pom.xml
- ui.config/src/main/content/jcr_root/apps/asset-share-commons/osgiconfig/config/com.adobe.aem.commons.assetshare.content.renditions.impl.dispatchers.AssetDeliveryRenditionDispatcherImpl~search-results_cloud.cfg.json
- ui.content.sample/pom.xml
- ui.content/pom.xml
- ui.frontend.theme.dark/pom.xml
- ui.frontend.theme.light/pom.xml
> Asset Rendition dispatcher tracking hook

- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/profile.js
Fix user information rendering when profile.json is not found. This is the case for us when we use LDAP login. 
https://github.com/adobe/asset-share-commons/issues/1000
see issue
Tested locally
> Fix user info rendering when profile.json isn't available

- ui.content.sample/src/main/content/jcr_root/content/asset-share-commons/en/dark/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/asset-share-commons/en/light/.content.xml
Missing default content results in What's new and FAQ pages to think the actions/downloads should beneath them, rather than the root "search" page.  This results in an empty downloads badge.
> Added missing downloads action URL to page properties

- all/pom.xml
- core.cloud/pom.xml
- core/pom.xml
- core/src/main/java/com/adobe/aem/commons/assetshare/components/details/impl/PdfImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/util/AdobePdfEmbedApi.java
- core/src/main/java/com/adobe/aem/commons/assetshare/util/impl/AdobePdfEmbedApiImpl.java
- dispatcher/pom.xml
- pom.xml
- ui.apps.structure/pom.xml
- ui.apps/pom.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/pdf/_cq_design_dialog/.content.xml
- ui.config/pom.xml
- ui.content.sample/pom.xml
- ui.content/pom.xml
- ui.frontend.theme.dark/pom.xml
- ui.frontend.theme.light/pom.xml
Added an OSGi configuration to configure the Adobe Embed PDF API client id. This allows for the client ID to be managed in Git for various tiers (Author vs Publish) and for different environments. This can also use Cloud Manager OSGi environemtn variables.
Any values set in the Design Dialog (Policy) for will supersede the OSGi configuration value.
> Added OSGi configuration for Adobe Embed PDF API client ID

- core/src/main/java/com/adobe/aem/commons/assetshare/util/impl/JsonResolverImpl.java
- core/src/test/java/com/adobe/aem/commons/assetshare/util/impl/JsonResolverImplTest.java
- core/src/test/resources/com/adobe/aem/commons/assetshare/util/impl/JsonResolverImpl--generic-list.json
The internal include of the generic list is problematic as it can infinite recursion.
This changes the implementation to simply grab the properties off the resources. This is simpler, and more straightforward.
+ + Tested on AEM CS SDK. 
Wrote Unit test.
> Fix issue when specifying Generic List as JSON source

- all/pom.xml
- core.cloud/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/AssetDeliveryRenditionDispatcherImpl.java
- core.cloud/src/test/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/AssetDeliveryRenditionDispatcherImplTest.java
- core.cloud/src/test/resources/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/AssetDeliveryRenditionDispatcherImplTest.json
- pom.xml
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/details/video/templates/player.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/clientlibs/site/js.txt
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/clientlibs/site/js/scripts.js
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/result/card/templates/card.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/result/horizontal-masonry-card/templates/card.html
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/result/list/templates/list.html
Fixed issue in AssetDelivery dispatcher where it would NPE if the dc:format property was not set on an asset (which appears to be the case for OFT files).
Also, added JS fallback support for imgs that dont load (to use the missing image, cliend-side).
> Fixed issue with thumbnails not showing for assets missing dc:format

- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/AbstractPredicate.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/PagePredicateImpl.java
> Fix issue with Initial values

- core/pom.xml
- core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareServiceImpl.java
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/share/_cq_dialog/.content.xml
Add tracking to Email share component.
> Adding share tracking

- .github/workflows/verify.yaml
- all/pom.xml
- core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/download/Download.java
- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/PagePredicateImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/properties/impl/ContentTypeImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/AssetRenditionDispatchersImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/search/impl/predicateevaluators/PropertyValuesPredicateEvaluator.java
- core/src/main/java/com/adobe/aem/commons/assetshare/util/impl/EmailServiceImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/workflow/assetkit/impl/AssetKitCreatorWorkflowProcess.java
- core/src/test/java/com/adobe/aem/commons/assetshare/content/impl/MetadataSchemaPropertiesImplTest.java
- core/src/test/java/com/adobe/aem/commons/assetshare/content/impl/datasources/AssetRenditionsDataSourceTest.java
- core/src/test/java/com/adobe/aem/commons/assetshare/content/renditions/download/impl/AssetRenditionsDownloadServletTest.java
- core/src/test/java/com/adobe/aem/commons/assetshare/content/renditions/download/impl/AssetRenditionsZipperImplTest.java
- core/src/test/java/com/adobe/aem/commons/assetshare/content/renditions/impl/AssetRenditionServletTest.java
- core/src/test/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/ExternalRedirectRenditionDispatcherImplTest.java
- core/src/test/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/InternalRedirectRenditionDispatcherImplTest.java
- core/src/test/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/StaticRenditionDispatcherImplTest.java
- core/src/test/java/com/adobe/aem/commons/assetshare/search/impl/FastPropertiesImplTest.java
- core/src/test/java/com/adobe/aem/commons/assetshare/search/impl/predicateevaluators/PropertyValuesPredicateEvaluatorTest.java
- core/src/test/java/com/adobe/aem/commons/assetshare/testing/RequireAemMock.java
- pom.xml
- ui.config/src/main/content/jcr_root/apps/asset-share-commons/osgiconfig/config.prod/org.apache.sling.commons.log.LogManager.factory.config~asset-share-commons.config
- ui.config/src/main/content/jcr_root/apps/asset-share-commons/osgiconfig/config.stage/org.apache.sling.commons.log.LogManager.factory.config~asset-share-commons.config
- ui.config/src/main/content/jcr_root/apps/asset-share-commons/osgiconfig/config/org.apache.sling.commons.log.LogManager.factory.config~asset-share-commons.config
- ui.content.sample/src/main/content/jcr_root/content/.content.xml
- ui.content.sample/src/main/content/jcr_root/content/dam/.content.xml
Removed use of Google Guava Collections and the org.apache.common uses I could (cannot replace StrLookup)
> Fixed issues (that have fixes) identified by AEM Analyse 1.6.6

- core.cloud/src/main/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/AssetDeliveryRenditionDispatcherImpl.java
- core.cloud/src/test/java/com/adobe/aem/commons/assetshare/content/renditions/impl/dispatchers/AssetDeliveryRenditionDispatcherImplTest.java
Replaced use of com.google.common Splitter with vanilla Java implemtation.
Fixes #1241
Google lib is deprecated.
Unit test
> Removed use of com.google.common

- core/pom.xml
FIxed #1250 - Relaxes certain imports required by AEM 6.5 SP18.
The newer package versions do change the functionality used by ASC.
> #1250 - Relaxed imports to support AEM 6.5 SP19

- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/modals/download/clientlibs/site/js/download.js
Fixes issue described in #1267 where the for loop is using ES6 syntax that AEM clientlib compiler doesnt like.
> Changed For loop in modal.js to use ES5-friendly syntax

- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-site/js/semantic-ui/modal.js
Fix bug with modals not appearing correctly when ASC loaded into an iFrame.
The browser throws a `SecurityError` when the js code tries to access properties of `window.top`, which is not accessible to javascript loaded in an iframe as `window.top` will point to a parent window. This fix reuses the `ns.Util.isSameOrigin()`  function to check if `window.top` will be allowed, and falls back to using the current window if not.
#1276 
We would like to host an ASC site within an iframe embed.
Tested fix in cross-domain iframe setting and fix seems to resolve issue.
> fix for ASC issue #1276 - modals not opening correctly when ASC loaded in iframe

- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/clientlibs/clientlib-author/js/authoring.js
Fixes #1292
Support PageEditor when a context path set; 
For example `author.com/foo-bar/editor.html/....`
It currently assumes the editor.html is loaded from the domain root (`author.com/editor.html/...`) which is the default behavior.
- [] My change requires a change to the documentation.
> Support page editor with context path

- core/src/main/java/com/adobe/aem/commons/assetshare/components/predicates/impl/FulltextPredicateImpl.java
- core/src/main/java/com/adobe/aem/commons/assetshare/search/impl/predicateevaluators/AiFulltextPredicateEvaluator.java
- core/src/main/java/com/adobe/aem/commons/assetshare/search/impl/predicateevaluators/AiSearchRenderCondition.java
- core/src/main/java/com/adobe/aem/commons/assetshare/search/impl/predicateevaluators/PropertyValuesPredicateEvaluator.java
- core/src/main/java/com/adobe/aem/commons/assetshare/search/providers/impl/QuerySearchProviderImpl.java
- core/src/test/java/com/adobe/aem/commons/assetshare/search/impl/predicateevaluators/AiFulltextPredicateEvaluatorTest.java
- ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/search-bar/_cq_dialog/.content.xml
Add support for AI Search in AEM as a Cloud Service.
Only display the toggle when the AEM is enabled to evaluate AI fulltext search requests.
1. Added a checkbox on the Search Bar dialog to enable AI Search
2. Created a AIFulltextSearchPredicate for querybuilder 
3. Toggle its use in the search-bar component based on if AI Search is enabled. If not enabled, it falls back to regular Fulltext predicate.
OOTB support for AEM as a Cloud Service AI Search in ASC.
AEM SDK and AEM s a Cloud Service sandbox.
> Added support for AI Search in AEM as a Cloud Service
